package GUI.Voyages;

import DB.*;
import GUI.Tickets.ListTickets;
import GUI.Tickets.SellTicket;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author alimu
 */
public class ListVoyage extends javax.swing.JInternalFrame {

    DB db = new DB(); 
    public ListVoyage() {
        initComponents();
        
        db.cities.getIller().forEach(item->{
            this.baslaIL.addItem(item.name);
            this.bitirIL.addItem(item.name);
        });
        db.cities.getIlceler(baslaIL.getSelectedIndex()+1).forEach(item->{
            baslaIlce.addItem(item.name);
        });
        db.cities.getIlceler(bitirIL.getSelectedIndex()+1).forEach(item->{
            bitirIlce.addItem(item.name);
        });
        baslaIL.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                baslaIlce.removeAllItems();
                db.cities.getIlceler(baslaIL.getSelectedIndex()+1).forEach(item->{
                    baslaIlce.addItem(item.name);
                });
                baslaIlce.setSelectedIndex(0);
            }
        });
        bitirIL.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                bitirIlce.removeAllItems();
                db.cities.getIlceler(bitirIL.getSelectedIndex()+1).forEach(item->{
                    bitirIlce.addItem(item.name);
                });
                bitirIlce.setSelectedIndex(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bitirIL = new javax.swing.JComboBox<>();
        bitirIlce = new javax.swing.JComboBox<>();
        anamenü1 = new javax.swing.JButton();
        baslaIL = new javax.swing.JComboBox<>();
        baslaIlce = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateChooserbasla = new com.toedter.calendar.JDateChooser();
        dateChooserBitir = new com.toedter.calendar.JDateChooser();
        anamenü3 = new javax.swing.JButton();
        anamenü4 = new javax.swing.JButton();
        anamenü2 = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sefer_id", "arac_id", "plaka", "sefer_saati", "sefer_tarihi", "sefer_nerden", "sefer_nereye"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jButton2.setText("Seferi Sil");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        anamenü1.setText("Seferleri getir");
        anamenü1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Başlangıç tarihi");

        jLabel2.setText("Bitiş Tarihi");

        jLabel3.setText("Kalkış Yeri");

        jLabel4.setText("Varış Yeri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(anamenü1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(baslaIL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(baslaIlce, 0, 137, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bitirIL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitirIlce, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserbasla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserBitir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(dateChooserbasla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserBitir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baslaIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baslaIlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitirIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bitirIlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anamenü1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        anamenü3.setText("Yolcuları Listele");
        anamenü3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü3ActionPerformed(evt);
            }
        });

        anamenü4.setText("Bilet Sat");
        anamenü4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü4ActionPerformed(evt);
            }
        });

        anamenü2.setText("Sefer Ekle");
        anamenü2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anamenü4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anamenü2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anamenü3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anamenü3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anamenü4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anamenü2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anamenü1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        db.voyages.getVoyages(
                dateChooserbasla.getCalendar().getTime(),
                dateChooserBitir.getCalendar().getTime(),
                db.cities.getIlceID(baslaIL.getSelectedIndex()+1,baslaIlce.getSelectedItem().toString()),
                db.cities.getIlceID(bitirIL.getSelectedIndex()+1,bitirIlce.getSelectedItem().toString())
        ).forEach((item) -> {
            model.addRow(new Object[]{
                item.seferID, 
                item.otobusID, 
                db.buses.getBus(item.otobusID).plaka, 
                item.kalkisTarih,
                item.varisTarih,
                baslaIlce.getSelectedItem().toString(),
                bitirIlce.getSelectedItem().toString()}
            );
        });
        
    }//GEN-LAST:event_anamenü1ActionPerformed

    private void anamenü2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü2ActionPerformed
      
        AddVoyage a  = new AddVoyage();
        a.setVisible(true);
        
    }//GEN-LAST:event_anamenü2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.voyages.delVoayage((int)table.getModel().getValueAt(table.getSelectedRow(), 0));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void anamenü3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü3ActionPerformed
        ListTickets lt = new ListTickets((int)table.getModel().getValueAt(table.getSelectedRow(), 0));
        
    }//GEN-LAST:event_anamenü3ActionPerformed

    private void anamenü4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü4ActionPerformed
        
        SellTicket view = new SellTicket((int)table.getModel().getValueAt(table.getSelectedRow(), 0));
        view.setVisible(true);
    }//GEN-LAST:event_anamenü4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anamenü1;
    private javax.swing.JButton anamenü2;
    private javax.swing.JButton anamenü3;
    private javax.swing.JButton anamenü4;
    private javax.swing.JComboBox<String> baslaIL;
    private javax.swing.JComboBox<String> baslaIlce;
    private javax.swing.JComboBox<String> bitirIL;
    private javax.swing.JComboBox<String> bitirIlce;
    private com.toedter.calendar.JDateChooser dateChooserBitir;
    private com.toedter.calendar.JDateChooser dateChooserbasla;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
