/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Tickets;
import DB.*;
import GUI.Dashboard;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omert
 */
public class ListTickets extends javax.swing.JFrame {

    /**
     * Creates new form ListTickets
     */
    int seyehatID;
    DB db = new DB();
    public ListTickets(int seyehatID) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setVisible(true);
        this.seyehatID = seyehatID;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        db.voyages.getClients(seyehatID).forEach((item) -> {
            model.addRow(new Object[]{item.id,item.firstname+" "+item.lastname,item.tc,item.gender,item.hescode,db.tickets.getChairNumber(item.id, seyehatID)});
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        anamenü1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        anamenü2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1135, 639));

        table.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "İsim Soyisim", "TC Kimlik No", "Telefon", "Hes Kodu", "Koltuk No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tableİnputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        anamenü1.setText("Bilet Sat");
        anamenü1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bilet Sil");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        anamenü2.setText("Bilet Güncelle");
        anamenü2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anamenü2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenü2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anamenü1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(anamenü2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anamenü1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anamenü2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableMouseClicked

    private void tableİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableİnputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tableİnputMethodTextChanged

    private void anamenü1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü1ActionPerformed
        
        SellTicket view = new SellTicket(seyehatID,this);
        view.setVisible(true);
       
    }//GEN-LAST:event_anamenü1ActionPerformed

    private void anamenü2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenü2ActionPerformed
        try {
            SellTicket view = new  SellTicket(seyehatID,(int)table.getModel().getValueAt(table.getSelectedRow(), 0),this);
            view.setVisible(true);
            this.updateTable();
        } catch (Exception e) {
            Dashboard.infoBoxView("Seçim yapınız", "Uyarı");
        }
        
    }//GEN-LAST:event_anamenü2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            db.tickets.delTicket((int)table.getModel().getValueAt(table.getSelectedRow(), 0), seyehatID);
        this.updateTable();
        } catch (Exception e) {
            Dashboard.infoBoxView("Seçim yapınız", "Uyarı");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void updateTable(){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        db.voyages.getClients(seyehatID).forEach((item) -> {
            model.addRow(new Object[]{item.id,item.firstname+" "+item.lastname,item.tc,item.gender,item.hescode,db.tickets.getChairNumber(item.id, seyehatID)});
            
        });
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anamenü1;
    private javax.swing.JButton anamenü2;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
